osx_image: xcode8.2
language: objective-c

script:
  - set -o pipefail
  - xcodebuild -project Example/TorXPCExample.xcodeproj -scheme TorXPCExample -sdk macosx -destination 'platform=OS X,arch=x86_64' build | xcpretty -c
